version: "3.3"

services:
  eudiw-issuer:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: "app"
      FLASK_RUN_PORT: "5000"
      FLASK_RUN_HOST: "0.0.0.0"
      SERVICE_URL: "https://127.0.0.1:5000/"
      EIDAS_NODE_URL: "https://preprod.issuer.eudiw.dev/EidasNode/"
      DYNAMIC_PRESENTATION_URL: "https://dev.verifier-backend.eudiw.dev/ui/presentations/"
      REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
      SSL_CERT_FILE: "/etc/ssl/certs/ca-certificates.crt"
    volumes:
      - ./config_secrets:/root/secrets:ro
      - ./pid-issuer:/etc/eudiw/pid-issuer:ro
      - ./pid-issuer:/etc/eudiw/pid-issuer-dev:ro
    command: sh -c "cp /root/secrets/config_secrets.py /root/eudi-srv-web-issuing-eudiw-py/app/app_config/ && flask run --cert=/root/secrets/cert.pem --key=/root/secrets/key.pem"
